//EMPLOYEE ACTIONS
export const GET_ALL_EMPLOYEES= "GET_ALL_EMPLOYEES";
export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
//CURRENT EMPLOYEE ACTIONS
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const UPDATING_EMPLOYEE = 'UPDATING_EMPLOYEE';
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
//FILTER ACTIONS
export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES"
export const SHOW_FILTER = "SHOW_FILTER";
export const HIDE_FILTER = "HIDE_FILTER";
export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";
//SKILL ACTIONS
export const ADD_SKILL = "ADD_SKILL";
export const REMOVE_SKILL = "REMOVE_SKILL";
//SEARCH ACTIONS
export const SELECT_SEARCH_CATERGORY = "SELECT_SEARCH_CATERGORY";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";
//LOADIN ACTIONS
export const LOADING = "LOADING";