

export const UPDATE_CURRENT_EMPLOYEES = "UPDATE_CURRENT_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";

export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const UPDATING_CURRENT_EMPLOYEE = 'UPDATING_CURRENT_EMPLOYEE';
export const UPDATE_CURRENT_EMPLOYEE = "UPDATE_CURRENT_EMPLOYEE";

export const SHOW_FILTER = "SHOW_FILTER";
export const HIDE_FILTER = "HIDE_FILTER";

export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const ADD_SKILL = "ADD_SKILL";
export const REMOVE_SKILL = "REMOVE_SKILL";

export const LOADING = "LOADING";

